### ISSUE TITLE
Create Stored Procedures

### ISSUE THREAD

**Issue by vineetdhammi** [ElectronicMenu/eMenu-Project#12]
create all the required stored procedures to read, insert, update, and delete

**Comment by Shobika** [comment]
Thank you vineet for assigning the task. I am working on creating the stored procedure for table "table" right now. Will let u know once I am done.

**Comment by Shobika** [comment]
Completed the stored procedures creation for table "table":
1. sp_table_insert
2. sp_table_deleteByID
3. sp_table_readByNum_readByPwd
4. sp_table_updateAllByID
And also uploaded in the shared database as well. Let me know in case of any issues or concerns.

**Comment by Shobika** [comment]
Working on creating the stored procedure for table "language" right now.

**Comment by Shobika** [comment]
Completed the stored procedures creation for table "language":
1. sp_language_insert
2. sp_language_deleteByID
3. sp_language_readByID
4. sp_language_updateAllByID
5. 3. sp_language_readAll
And also uploaded in the shared database as well. Let me know in case of any issues or concerns.

**Comment by Shobika** [comment]
Working on creating the stored procedure for table "category & categorylanguage" right now.

**Comment by Shobika** [comment]
Completed the stored procedures creation for table "category & category_language":
1. sp_category_category_language_deleteByID
2. sp_category_category_language_insert
3. sp_category_category_language_readByID
4. sp_category_category_language_readAll
And also uploaded in the shared database as well. Let me know in case of any issues or concerns.

**Comment by vineetdhammi** [comment]
Hey Shobika, Please provide me the stored procedures to work with "order" and "order_details" tables.

**Comment by Shobika** [comment]
Working on it..will update you once I am done..

**Comment by Shobika** [comment]
Created stored procedure for Order insert and Order details insert based on cart ID. Commited to Git.
