### ISSUE TITLE
Auto-generated column values in the product table

### ISSUE THREAD

**Issue by vineetdhammi** [ElectronicMenu/eMenu-Project#13]
Make the product_final_price column of product table to auto calculate the final price depending on the discount type (whether is it 0 = none; 1 = percentage; 2 = price).

**Comment by Shobika** [comment]
Hey Vineet, Working on this, wil let u know once I am done.

**Comment by Shobika** [comment]
Hey vineet, i have completed the product table final price calculation..uploaded the script in the online database with some sample data..so now you can work on APIs for product table.
