### ISSUE TITLE
Create new tables and stored procedures

### ISSUE THREAD

**Issue by vineetdhammi** [ElectronicMenu/eMenu-Project#18]
As we discussed in our last meeting, create the 3 new tables and required stored procedures for these tables....
1. cart table
2. cart_product table
3. user table

**Comment by Shobika** [comment]
Hey Vineet, Will work on the task and let you know once I am done..

**Comment by Shobika** [comment]
created 3 new tables..shared in the online database ..you can use it for APIs..now working on stored procedures.

**Comment by Shobika** [comment]
Hey vineet, completed the stored procedures for the above mentioned table..will assign the pull request task to you , so that you can work on APIs.
