### ISSUE TITLE
Create Web APIs to Read the data different tables

### ISSUE THREAD

**Issue by hlac** [ElectronicMenu/eMenu-Project#4]
#3

**Comment by Shobika** [comment]
This task includes creation of Web APIs for all the tables designed.

**Comment by vineetdhammi** [comment]
Thank you Shobika for assigning the tasks. Before I start working on APIs, I want you and Sachet to create the database design and tables, and share the database with me. Then I will start working on the APIs

**Comment by Shobika** [comment]
Added milestone..

**Comment by vineetdhammi** [comment]
Created all the web APIs required for eMenu mobile app.
http://emenu.dhammi.com/Help
