### ISSUE TITLE
Create tables for the database

### ISSUE THREAD

**Issue by Shobika** [ElectronicMenu/eMenu-Project#5]
Tables required for the application like categories , products, tables, category_language etc., and also their relationships between the different tables
 #1

**Comment by Shobika** [comment]
[sqlv1.0.zip](https://github.com/ElectronicMenu/eMenu-Project/files/129891/sqlv1.0.zip)

Hey Vineet... I have created the database with some sample data as discussed in our previous meeting. you can start creating Web APIs. let me know if you need me to make any updates or addition in the database

**Comment by vineetdhammi** [comment]
Thank you Shobika for your work. I will start working on the Web APIs
